# Generated by Django 3.2.9 on 2021-12-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='password',
            field=models.CharField(max_length=400),
        ),
    ]
