# Generated by Django 3.2.9 on 2021-12-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_alter_input_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='password',
            field=models.BinaryField(max_length=400),
        ),
    ]
