# Generated by Django 3.2.9 on 2021-12-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_alter_input_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='site_name',
            new_name='sitename',
        ),
        migrations.RenameField(
            model_name='input',
            old_name='website_url',
            new_name='websiteurl',
        ),
    ]
